version: '3.4'
services:

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_DB=telegramdb
      - POSTGRES_USER=telegram
      - POSTGRES_PASSWORD=telegram
      - POSTGRES_SCHEMA=telegram
    ports:
# for debugging, can be disabled
      - "5431:5432"

  pogorobot:
    container_name: pogorobot
    image: pogorobot:latest
    environment:
      - TZ=Europe/Berlin
    build: 
      context: ./
      args:
        - JAR_FILE=pogorobot-postgres-1.1.1-SNAPSHOT-exec.jar
    depends_on:
      - postgres
    ports:
# format: "port-on-docker-host:port-in-docker-container"
# webhook port
      - "8080:8080"
# debug ports
      - "12345:8800"
      - "8810:8810"
    volumes:
# mount local directories in docker-container
      - ./config:/config
      - ./logs:/logs

volumes:
  config:
    driver: local
  logs:
    driver: local
